[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "CI= npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[[scheduled]]
  function = "generateSitemap"
  schedule = "@daily"

[[plugins]]
package = "@netlify/plugin-functions-install-core"
